server:
  port: 8090

spring:
  application:
    name: demo-test
    profiles:
      active: dev
  datasource:
    username: root
    password: Haidao!@#$%^&*()690159
    url: jdbc:mysql://120.77.207.4:3306/siycrm?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    jdbc.driverClassName: com.mysql.jdbc.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.hdedu: debug
  config: classpath:logback.xml
