server:
  port: 8090

spring:
  application:
    name: demo-test
    profiles:
      active: dev
  datasource:
    username: root
    password: Haidao!@#$%^&*()690159
    url: jdbc:mysql://120.77.207.4:3306/hdweb?serverTimezone=UTC
    jdbc.driverClassName: com.mysql.jdbc.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

nacos:
  namespace: dev
  server-addr: 127.0.0.1:8848
  auto-refresh: true
  group: demo

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl